
 

services:
  app:
    build: .
    ports:
      - "8940:8940"
    environment:
      - PORT=${PORT}
      - GAME_HOST=${GAME_HOST}
      - REPLAY_HOST=${REPLAY_HOST}
      - REAL_GAME_HOST=${REAL_GAME_HOST}
      - ASSET_HOST=${ASSET_HOST}
      - PROMO_HOST=${PROMO_HOST}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BuyBonusDefaultMulti=${BuyBonusDefaultMulti}
      - FreeMinMulti=${FreeMinMulti}
      - JackpotNormalStart=${JackpotNormalStart}
      - JackpotNormalEnd=${JackpotNormalEnd}
      - JackpotLongPercent=${JackpotLongPercent}
      - JackpotLongStart=${JackpotLongStart}
      - JackpotLongEnd=${JackpotLongEnd}
      - SmallBaseMaxMulti=${SmallBaseMaxMulti}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=a2pe4zx5p1
      - MYSQL_DATABASE=game_db
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
  