# Используем официальный образ Node.js (LTS версия)
FROM node:22-alpine as builder

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json (если есть) для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь исходный код приложения
COPY . .

# Указываем порт, который будет открыт
EXPOSE 8940


# Команда для запуска приложения
CMD ["node", "server.js"]