module.exports = (app) => {
  const games = [
    { g_name: "vs20doghouse", g_title: "The_Dog_House" },
    { g_name: "vs40pirate", g_title: "Pirate_Gold" },
    { g_name: "vs20rhino", g_title: "Great_Rhino" },
    { g_name: "vs243mwarrior", g_title: "Monkey_Warrior" },

    { g_name: "vswaysdogs", g_title: "Dog_House_Megaways" },
    // { g_name: "vs25pandagold", g_title: "Panda_Fortune" },
    // { g_name: "vs25pyramid", g_title: "Pyramid_King" },
    // { g_name: "vs4096bufking", g_title: "Buffalo_King" },
    // { g_name: "vs25aztecking", g_title: "Aztec_King" },
    // { g_name: "vs25jokerking", g_title: "Joker_King" },
    // { g_name: "vs5ultrab", g_title: "Ultra_Burn" },
    // { g_name: "vs5ultra", g_title: "Ultra_Hold" },
    // { g_name: "vs10returndead", g_title: "Return_Dead" },
    // { g_name: "vs10madame", g_title: "Madame_Destiny" },
    // { g_name: "vs15diamond", g_title: "Diamond_Strike" },
    // { g_name: "vs10bbbonanza", g_title: "Big_Bass_Bonanza" },
    // { g_name: "vs10cowgold", g_title: "Cowboys_Gold" },
    // { g_name: "vs25tigerwar", g_title: "The_Tiger_Warrior" },
    // { g_name: "vs25wildspells", g_title: "Wild_Spells" },
    // { g_name: "vs25mustang", g_title: "Mustang_Gold" },
    // { g_name: "vs25hotfiesta", g_title: "Hot_Fiesta" },
    // { g_name: "vs243dancingpar", g_title: "Dance_Party" },
    // { g_name: "vs20hburnhs", g_title: "Hot_To_Burn" },
    // { g_name: "vs576treasures", g_title: "Wild_Wild_Riches" },
    // { g_name: "vs20emptybank", g_title: "Empty_The_Bank" },
    // { g_name: "vs20vegasmagic", g_title: "Vegas_Magic" },
    // { g_name: "vs20olympgate", g_title: "Gates_Of_Olympus" },
    // { g_name: "vs20midas", g_title: "The_Hand_Of_Midas" },
    // { g_name: "vswayslight", g_title: "Lucky_Lightning" },
    // { g_name: "vs20fruitparty", g_title: "Fruit_Party" },
    // { g_name: "vs20fparty2", g_title: "Fruit_Party_2" },
    // { g_name: "vswaysdogs", g_title: "Dog_House_Megaways" },
    // { g_name: "vs50juicyfr", g_title: "Juicy_Fruits" },
    // { g_name: "vs25pandatemple", g_title: "Panda_Fortune_2" },
    // { g_name: "vswaysbufking", g_title: "Buffalo_King_Megaways" },
    // { g_name: "vs40wildwest", g_title: "Wild_West_Gold" },
    // { g_name: "vswaysrhino", g_title: "Great_Rhino_Megaways" },
    // { g_name: "vs20sbxmas", g_title: "Sweet_Bonanza_Xmas" },
    // { g_name: "vs40spartaking", g_title: "Spartan_King" },
    // { g_name: "vs20chickdrop", g_title: "Chicken_Drop" },
    // { g_name: "vs10fruity2", g_title: "Extra_Juicy" },
    // { g_name: "vs10egypt", g_title: "Ancient_Egypt" },
    // { g_name: "vs20tweethouse", g_title: "Tweety_House" },
    // { g_name: "vs5drhs", g_title: "Dragon_Hold_and_Spin" },
    // { g_name: "vswayssamurai", g_title: "Samurai_Megaways" },
    // { g_name: "vs12bbb", g_title: "Bigger_Bass_Bonanza" },
    // { g_name: "vswayslions", g_title: "5_Lions_Megaways" },
    // { g_name: "vs50pixie", g_title: "Pixie_Wings" },
    // { g_name: "vs10floatdrg", g_title: "Floating_Dragon" },
    // { g_name: "vs20fruitsw", g_title: "Sweet_Bonanza" },
    // { g_name: "vs20rhinoluxe", g_title: "Great_Rhino_Deluxe" },
    // { g_name: "vs432congocash", g_title: "Congo_Cash" },
    // { g_name: "vswaysmadame", g_title: "Madame_Destiny_Megaways" },
    // { g_name: "vs1024temuj", g_title: "Temujin_Treasures" },
    // { g_name: "vs40pirgold", g_title: "Pirate_Gold_Deluxe" },
    // { g_name: "vs25mmouse", g_title: "Money_Mouse" },
    // { g_name: "vs10threestar", g_title: "Three_Star_Fortune" },
    // { g_name: "vs1ball", g_title: "Lucky_Dragon_Ball" },
    // { g_name: "vs243lionsgold", g_title: "Lions_Gold" },
    // { g_name: "vs10egyptcls", g_title: "Ancient_Egypt_Classic" },
    // { g_name: "vs25davinci", g_title: "Da_Vinci_Treasure" },
    // { g_name: "vs7776secrets", g_title: "Aztec_Treasure" },
    // { g_name: "vs25wolfgold", g_title: "Wolf_Gold" },
    // { g_name: "vs50safariking", g_title: "Safari_King" },
    // { g_name: "vs25peking", g_title: "Peking_Luck" },
    // { g_name: "vs25asgard", g_title: "Asgard" },
    // { g_name: "vs25vegas", g_title: "Vegas_Night" },
    // { g_name: "vs75empress", g_title: "Golden_Beauty" },
    // { g_name: "vs25scarabqueen", g_title: "Scarab_Queen" },
    // { g_name: "vs20starlight", g_title: "Starlight_Princess" },
    // { g_name: "vs10bookoftut", g_title: "Book_of_Tut" },
    // { g_name: "vs9piggybank", g_title: "Piggy_Bank" },
    // { g_name: "vs5drmystery", g_title: "Dragon_Kingdom" },
    // { g_name: "vs20eightdragons", g_title: "Eight_Dragons" },
    // { g_name: "vs1024lionsd", g_title: "Lions_Dance" },
    // { g_name: "vs25rio", g_title: "Heart_Of_Rio" },
    // { g_name: "vs10nudgeit", g_title: "Nud_Geit" },
    // { g_name: "vs10bxmasbnza", g_title: "Christmas_Bonanza" },
    // { g_name: "vs20santawonder", g_title: "Santa_Wonder" },
    // { g_name: "vs20terrorv", g_title: "Cash_Elevator" },
    // { g_name: "vs10bblpop", g_title: "Bubble_Pop" },
    // { g_name: "vs25btygold", g_title: "Bounty_Gold" },
    // { g_name: "vs88hockattack", g_title: "Hockey_Attack" },
    // { g_name: "vswaysbbb", g_title: "Big_Bass_Mega" },
    // { g_name: "vs10bookfallen", g_title: "Book_Of_Fallen" },
    // { g_name: "vs40bigjuan", g_title: "Big_Juan" },
    // { g_name: "vs20bermuda", g_title: "John_Bermuda" },
    // { g_name: "vs10starpirate", g_title: "Star_Pirates_Code" },
    // { g_name: "vswayswest", g_title: "Mystic_Chief" },
    // { g_name: "vs20daydead", g_title: "Day_Of_Dead" },
    // { g_name: "vs20candvil", g_title: "Candy_Village" },
    // { g_name: "vs20wildboost", g_title: "Wild_Booster" },
    // { g_name: "vswayshammthor", g_title: "Power_Of_Thor_Mega" },
    // { g_name: "vs243lions", g_title: "Five_Lion" },
    // { g_name: "vs5super7", g_title: "Super_Seven" },
    // { g_name: "vs1masterjoker", g_title: "Master_Joker" },
    // { g_name: "vs20kraken", g_title: "Release_Kraken" },
    // { g_name: "vs10firestrike", g_title: "Fire_Strike" },
    // { g_name: "vs243fortune", g_title: "Caishen_Gold" },
    // { g_name: "vs4096mystery", g_title: "Mysterious" },
    // { g_name: "vs20aladdinsorc", g_title: "Aladdin_Sorcer" },
    // { g_name: "vs243fortseren", g_title: "Greek_Gods" },
    // { g_name: "vs25chilli", g_title: "Chilly_Heat" },
    // { g_name: "vs8magicjourn", g_title: "Magic_Journey" },
    // { g_name: "vs25pantherqueen", g_title: "Panther_Queen" },
    // { g_name: "vs20leprexmas", g_title: "Leprechaun_Carol" },
    // { g_name: "vs7pigs", g_title: "Seven_Pigs" },
    // { g_name: "vs243caishien", g_title: "Caishen_Cash" },
    // { g_name: "vs5joker", g_title: "Joker_Jewels" },
    // { g_name: "vs25gladiator", g_title: "Wild_Gladiator" },
    // { g_name: "vs25goldpig", g_title: "Golden_Pig" },
    // { g_name: "vs25goldrush", g_title: "Goldrush" },
    // { g_name: "vs25dragonkingdom", g_title: "Dragon_Kingdom" },
    // { g_name: "vs25kingdoms", g_title: "Three_Kingdoms" },
    // { g_name: "vs1dragon8", g_title: "Dragon_888" },
    // { g_name: "vs5aztecgems", g_title: "Aztec_Gems" },
    // { g_name: "vs20hercpeg", g_title: "Hercules_Pegasus" },
    // { g_name: "vs7fire88", g_title: "Fire_88" },
    // { g_name: "vs20honey", g_title: "Honey" },
    // { g_name: "vs25safari", g_title: "Hot_Safari" },
    // { g_name: "vs25journey", g_title: "Seyugi" },
    // { g_name: "vs20chicken", g_title: "The_Great_Chicken" },
    // { g_name: "vs1fortunetree", g_title: "Fortune_Tree" },
    // { g_name: "vs20wildpix", g_title: "Wild_Pixies" },
    // { g_name: "vs15fairytale", g_title: "Fairy_Tale" },
    // { g_name: "vs20santa", g_title: "Santa" },
    // { g_name: "vs10vampwolf", g_title: "Vampire_Wolfes" },
    // { g_name: "vs50aladdin", g_title: "3_Genie_Wishes" },
    // { g_name: "vs50hercules", g_title: "Hercules" },
    // { g_name: "vs7776aztec", g_title: "Aztec_Bonanza" },
    // { g_name: "vs5trdragons", g_title: "Triple_Dragons" },
    // { g_name: "vs40madwheel", g_title: "Wild_Machine" },
    // { g_name: "vs25newyear", g_title: "Lucky_New_Year" },
    // { g_name: "vs40frrainbow", g_title: "Fruit_Rainbow" },
    // { g_name: "vs50kingkong", g_title: "Mighty_Kong" },
    // { g_name: "vs20godiva", g_title: "L_Godiba" },
    // { g_name: "vs9madmonkey", g_title: "Mad_Monkey" },
    // { g_name: "vs1tigers", g_title: "Triple_Tigers" },
    // { g_name: "vs9chen", g_title: "Master_Chens_Fortune" },
    // { g_name: "vs5hotburn", g_title: "Hot_To_Burn" },
    // { g_name: "vs25dwarves_new", g_title: "Dwarven_Gold_Deluxe" },
    // { g_name: "vs20leprechaun", g_title: "Leprechaun_Song" },
    // { g_name: "vs7monkeys", g_title: "Seven_Monkeys" },
    // { g_name: "vs18mashang", g_title: "Treasure_Horse" },
    // { g_name: "vs5spjoker", g_title: "Super_Joker" },
    // { g_name: "vs20egypttrs", g_title: "Egypt_Fortune" },
    // { g_name: "vs9hotroll", g_title: "Hot_Roll" },
    // { g_name: "vs4096jurassic", g_title: "Jurassic_Giants" },
    // { g_name: "vs3train", g_title: "Gold_Train" },
    // { g_name: "vs40beowulf", g_title: "Beowulf" },
    // { g_name: "vs1024atlantis", g_title: "Queen_of_Atlantis" },
    // { g_name: "vs243crystalcave", g_title: "Magic_Crystal" },
    // { g_name: "vs5trjokers", g_title: "Triple_Jokers" },
    // { g_name: "vs1money", g_title: "Money" },
    // { g_name: "vs75bronco", g_title: "Bronco_Spirit" },
    // { g_name: "vs1600drago", g_title: "Drago_Jewels" },
    // { g_name: "vs1fufufu", g_title: "Fu_Fu_Fu" },
    // { g_name: "vs40streetracer", g_title: "Street_Racer" },
    // { g_name: "vs9aztecgemsdx", g_title: "Aztec_Gems_Deluxe" },
    // { g_name: "vs20gorilla", g_title: "Jungle_Gorilla" },
    // { g_name: "vswayswerewolf", g_title: "Werewolf_Megaways" },
    // { g_name: "vswayshive", g_title: "Star_Bounty" },
    // { g_name: "vs25samurai", g_title: "Rise_of_Samurai" },
    // { g_name: "vs25walker", g_title: "Wild_Walker" },
    // { g_name: "vs20goldfever", g_title: "Gold_Fever" },
    // { g_name: "vs25bkofkngdm", g_title: "Book_Of_Kingdom" },
    // { g_name: "vs10goldfish", g_title: "Fish_In_Reels" },
    // { g_name: "vs1024dtiger", g_title: "Dragon_Tiger" },
    // { g_name: "vs20eking", g_title: "Emerald_King" },
    // { g_name: "vs20xmascarol", g_title: "Christmas_Carol_Mega" },
    // { g_name: "vs10mayangods", g_title: "John_Hunter_And_Mayan_Gods" },
    // { g_name: "vs20bonzgold", g_title: "Bonanza_Gold" },
    // { g_name: "vs25gldox", g_title: "Golden_Ox" },
    // { g_name: "vs10wildtut", g_title: "Mysterious_Egypt" },
    // { g_name: "vs20ekingrr", g_title: "Emerald_King_Rainbow" },
    // { g_name: "vs10eyestorm", g_title: "Eye_Of_Storm" },
    // { g_name: "vs117649starz", g_title: "Stars_Megaways" },
    // { g_name: "vs10amm", g_title: "Amazing_Machine" },
    // { g_name: "vswaysyumyum", g_title: "Yum_Yum_Powerways" },
    // { g_name: "vswayschilheat", g_title: "Chilli_Heat_Megaways" },
    // { g_name: "vs10luckcharm", g_title: "Lucky_Grace_And_Charm" },
    // { g_name: "vswaysaztecking", g_title: "Aztec_King_Mega" },
    // { g_name: "vs20phoenixf", g_title: "Phoenix" },
    // { g_name: "vs576hokkwolf", g_title: "Hokk_Wolf" },
    // { g_name: "vs20trsbox", g_title: "Treasure_Wild" },
    // { g_name: "vs243chargebull", g_title: "Raging_Bull" },
    // { g_name: "vs20pbonanza", g_title: "Pyramid_Bonanza" },
    // { g_name: "vs243empcaishen", g_title: "Emp_Caishen" },
    // { g_name: "vs25tigeryear", g_title: "Lucky_New_Year" },
    // { g_name: "vs20amuleteg", g_title: "Fortune_of_Giza" },
    // { g_name: "vs10runes", g_title: "Gates_Of_Valhalla" },
    // { g_name: "vs25goldparty", g_title: "Gold_Party" },
    // { g_name: "vswaysxjuicy", g_title: "Extra_Juicy_Mega" },
    // { g_name: "vs40wanderw", g_title: "Wild_Depth" },
    // { g_name: "vs4096magician", g_title: "Magician_Secret" },
    // { g_name: "vs20smugcove", g_title: "Smugglers_Cove" },
    // { g_name: "vswayscryscav", g_title: "Crystal_Cavens_Mega" },
    // { g_name: "vs5aztecgems_jp", g_title: "Aztec" },
    // { g_name: "vswayslofhero", g_title: "Legend_Of_Heroes" },
  ];
  // Define createOrFindGame
  const createOrFindGame = async () => {
    try {
      for (const game of games) {
        const [gameInstance, created] = await app.db.Game.findOrCreate({
          where: { g_name: game.g_name },
          defaults: {
            g_name: game.g_name,
            g_title: game.g_title,
            // createdAt and updatedAt are managed by Sequelize automatically
          },
        });
        console.log(`Game ${game.g_title} ${created ? "created" : "found"}`);
      }
    } catch (error) {
      console.error("Error creating or finding game:", error);
      throw error;
    }
  };

  // Define createOrFindUser
  const createOrFindUser = async () => {
    try {
      const [user, created] = await app.db.User.findOrCreate({
        where: { login: "test_user", email: "test@example.com" },
        defaults: {
          login: "test_user",
          email: "test@example.com",
          token: "test_token_123",
          balance: 100000,
          realRtp: 0,
          targetRtp: 500,
          totalDebit: 0,
          totalCredit: 0,
          // createdAt and updatedAt are managed by Sequelize automatically
        },
      });
      console.log(
        created ? "User created" : "User already exists",
        user.toJSON()
      );
      return user;
    } catch (error) {
      console.error("Error creating or finding user:", error);
      throw error;
    }
  };

  // Return an object containing the functions
  return {
    createOrFindGame,
    createOrFindUser,
  };
};
